channel/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from home import views

urlpatterns = [
    url(r'^logout/$', views.Logout.as_view(), name='logout'),
    url(r'^login/$', views.Login.as_view(), name='login'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^chat/', include('chat.urls', namespace='chat')),
]

chat/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.Index.as_view(chat_group='home'), name='chat'),
    url(r'^(?P<chat_group>[\w]+)/$', views.Index.as_view(), name='group'),
]

home/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.LoginRegister.as_view(), name='login-register'),
    url(r'^login/$', views.Login.as_view(), name='login'),
    url(r'^register/$', views.Register.as_view(), name='register'),
    url(r'^logout/$', views.Logout.as_view(), name='logout'),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class ChatGroup(models.Model):
    name = models.CharField(max_length=245)

    def __str__(self):
        return self.name

class UserChatGroup(models.Model):
    user = models.ForeignKey('Profile', on_delete=models.CASCADE)
    group = models.ForeignKey('ChatGroup')

    def __str__(self):
        return self.user.user.username + ' ' + self.group.name

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class Register(UserCreationForm):
    class Meta:
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2')


class Login(AuthenticationForm):
    class Meta:
        fields = ('username', 'password')

user_profile/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class Register(UserCreationForm):
    class Meta:
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2')


class Login(AuthenticationForm):
    class Meta:
        fields = ('username', 'password')

chat/views.py
from django.shortcuts import render
from django.views.generic import View


class Index(View):
    template_name = 'chat/index.html'
    chat_group= None

    def get(self, request, *args, **kwargs):
        if self.chat_group is None:
            self.chat_group = self.kwargs['chat_group']
        return render(request, self.template_name, {'chat_group':
                      self.chat_group})

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin


class LoginRegister(View):
    template_name = 'user_profile/index.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('chat:index')

        login_form = AuthenticationForm()
        register_form = UserCreationForm()
        return render(request, self.template_name,
                      {'login_form': login_form, 'register_form': register_form})

class Login(View):
    template_name = 'user_profile/index.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('chat:index')

        login_form = AuthenticationForm()
        return render(request, self.template_name,
                      {'login_form': login_form})

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('chat:index')

        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = authenticate(username=login_form.cleaned_data['username'],
                                password=login_form.cleaned_data['password'])

            if user.is_active:
                login(request, user)
                return redirect('chat:index')

        return render(request, self.template_name,
                      {'login_form': login_form})


class Register(View):
    template_name = 'user_profile/index.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('chat:index')

        register_form = UserCreationForm()
        return render(request, self.template_name,
                      {'register_form': register_form})

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('chat:index')

        register_form = UserCreationForm(data=request.POST)

        if register_form.is_valid():
            new_user = register_form
            register_form.save()
            user = authenticate(username=new_user.cleaned_data['username'],
                                password=new_user.cleaned_data['password1'])


            if user.is_active:
                login(request, user)
                return redirect('chat:index')

        return render(request, self.template_name,
                      {'register_form': register_form})


class Logout(LoginRequiredMixin, View):
    login_url = 'user-profile:login-register'

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('user-profile:login-register')

chat/templates/chat/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" ng-app="chatApp">
<head>
    <meta charset="UTF-8">
    <title>LearningWithWebsockets - {% block title %}Home{% endblock %}</title>

    {% block extra_styles %}
    {% endblock %}
</head>


{% block content %}
    <body>
    <h1>Hello there is no content!</h1>
{% endblock %}

{% block extra_js %}
    <script>
    </script>
{% endblock %}
</body>
</html>

chat/templates/chat/index.html
{% extends "chat/base.html" %}
{% load static %}

{% block title %}Chat{% endblock %}

{% block extra_styles %}
{% endblock %}

{% block content %}
    {% include "chat/navbar.html" %}
    {{ chat_group }}
    <div>
        <div>
            <ul>
                <li>[[ msg.user ]]: [[ msg.msgText ]]</li>
            </ul>
        </div>
    </div>

    <footer>
        <div>
            <form>
                <input class="" type="text" id="msgText">
                <label class="" for="msgText">Message text....</label>
                <button type="submit">
                    Send Message
                </button>
            </form>
        </div>
    </footer>
{% endblock %}

{% block extra_js %}
    <script>
		var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
		var dataStream = $websocket(ws_scheme.concat('://', window.location.host, '/{{ chat_room }}/'));
    </script>
{% endblock %}

chat/templates/chat/navbar.html
<nav>
</nav>

home/templates/user_profile/index.html
{% extends "home/base.html" %}
{% block title %}Login/Register{% endblock %}

{% block content %}
<div>
    <div>
    {% if login_form %}
        <form method="POST" action="{% url "home:login" %}">
            {% csrf_token %}
            <ul>
                {{ login_form.as_ul }}
                <li><input type="submit" value="Login"></li>
            </ul>
        </form>
    {% endif %}
</div>

<div>
    {% if register_form %}
        <form method="POST" action="{% url "home:register" %}">
            {% csrf_token %}
            <ul>
                {{ register_form.as_ul }}
                <li><input type="submit" value="Register"></li>
            </ul>
        </form>
    {% endif %}
</div>
</div>
{% endblock %}

{% block extra_js %}
    <script>
    </script>
{% endblock %}